### PR TITLE
SUMO-242708: Cutting new TF Release (2.31.0)

### PR DESCRIPTION
**Pull request by adisuj**
Updated CHANGELOG.md to reflect new release and its relevant changes

### CODE REVIEW

**Review by sumo-drosiek — APPROVED** [review]
:yay:

**Review by dagould — APPROVED** [review]
lgtm

**Comment by sumo-drosiek** [comment]
Checks do not run because of those lines:

https://github.com/SumoLogic/terraform-provider-sumologic/blob/c9f2f0667e54e6c263d9945375e5eb352501ae9d/.github/workflows/test.yml#L10
https://github.com/SumoLogic/terraform-provider-sumologic/blob/master/.github/workflows/tfproviderlint.yml#L16=

**Comment by adisuj** [comment]
> Checks do not run because of those lines:
> 
> https://github.com/SumoLogic/terraform-provider-sumologic/blob/c9f2f0667e54e6c263d9945375e5eb352501ae9d/.github/workflows/test.yml#L10
> 
> 
> https://github.com/SumoLogic/terraform-provider-sumologic/blob/master/.github/workflows/tfproviderlint.yml#L16=

I believe it is [expected](https://github.com/Sanyaku/codelabs/blob/master/backend/pages/SumoLogicTerraformProvider.md#cutting-a-new-release) the checks won't run as this is a non-code change. Once I get Vishal's approval, I'll continue with the process of cutting the new release.

**Review by ashpaliwal — APPROVED** [review]

**Review by sumovishal — APPROVED** [review]
LGTM, thanks for fixing the security issues.

**Pull request merged**
