### PR TITLE
Creating a data source for admin_recommended folder

### PR DESCRIPTION
**Pull request by karthich**
# sumologic_admin_recommended_folder
Provides an easy way to retrieve the Admin Recommended folder.

## Example Usage
```hcl
data "sumologic_admin_recommended_folder" "admin_recommended_folder" {}
```

## Attributes reference

The following attributes are exported:

- `id` - The ID of the Personal Folder.
- `name` - The name of the Personal Folder.
- `description` - The description of the Personal Folder.

### CODE REVIEW

**Comment by karthich** [comment]
First time PR to this project. Do the maintainers have any suggestions on how I can run acceptance tests without using my company sumologic account? Is there a free tier I can sign up for myself?

**Comment by seansain** [comment]
@karthich Thank you for opening up this PR for admin recommended folder! Yes, there is a free tier which you can sign up for [here](https://www.sumologic.com/sign-up/). I will also run them through GitHub Actions on the PR.

**Comment by karthich** [comment]
@seansain the errors in the pipeline seems to suggest that the pipeline is missing various environment variables. Should I set something up in my fork in order for it to pick it up. What is the procedure here?

**Comment by seansain** [comment]
@karthich I can try to move the PR to within the repo so we can just run the acceptance tests if you prefer.

**Comment by karthich** [comment]
Sounds good! Go ahead.

**Comment by seansain** [comment]
Re-raised in #215

**Pull request closed without merging**
