### PR TITLE
Adding validations for `name`, `description` and `payload_override` in monitors resource

### PR DESCRIPTION
**Pull request by tarunk2**
Github issue: https://github.com/SumoLogic/terraform-provider-sumologic/issues/195

### CODE REVIEW

**Review by gchairuangsang — APPROVED** [review]
lgtm

**Comment by sumovishal** [comment]
@tarunk2 can we update the CHANGELOG with this PR? 

I assume this will not impact any existing users, as these validations were present in the API layer?

**Comment by tarunk2** [comment]
> I assume this will not impact any existing users, as these validations were present in the API layer?

Correct. We plan to add more such validations in the future. Is the recommendation to add all these PRs to CHANGELOG? The reason I am asking this is because all these PRs will be for the same github issue (#195) and we plan to add all these validations incrementally over multiple PRs.

**Comment by sumovishal** [comment]
>Is the recommendation to add all these PRs to CHANGELOG? The reason I am asking this is because all these PRs will be for the same github issue (https://github.com/SumoLogic/terraform-provider-sumologic/issues/195) and we plan to add all these validations incrementally over multiple PRs.

Yeah, you can add them incrementally. In the changelog, we add links to GitHub PRs not the issue. For this one, the changelog entry can be 

```
BUG FIXES:
* Adding validations for name, description and payload_override (GH-420).
```

**Comment by tarunk2** [comment]
Will do, thanks

**Comment by tarunk2** [comment]
https://github.com/SumoLogic/terraform-provider-sumologic/pull/425

**Pull request merged**
