### PR TITLE
Add support for install, uninstall and upgrade apps in tf provider

### PR DESCRIPTION
**Pull request by sjain05**
Screenshot 2024-01-19 at 9 55 08 AM

### CODE REVIEW

**Comment by sjain05** [comment]
I am getting 
```Error: ***"id":"RF0SP-FTMNW-2FRJW","errors":[***"code":"api_not_enabled","message":"This API is not enabled for your organization."***]***``` but the test run locally fine where i run them against epdData org on stag

**Comment by dagould** [comment]
> ... in the Matrix Test pr builder job. Which org does it uses?

The org is "Terraform Testing" in us2.

**Comment by sjain05** [comment]
plox test

**Review by omid-mortazavi — APPROVED** [review]

**Review by dagould — APPROVED** [review]
lgtm

**Pull request merged**
