### PR TITLE
Using new template variables in connections in TF examples and tests

### PR DESCRIPTION
**Pull request by tarunk2**

### CODE REVIEW

**Comment by dstephens5** [comment]
Looks like one of the PR test jobs is failing but everything looks good to me

**Comment by seansain** [comment]
Ahhh looks like the tests failed because the fork doesn't have access to the secrets. LGTM otherwise.

**Comment by rsanbhad** [comment]
@dstephens5 @tarunk2 re-raised same PR from origin repo instead of fork for PR builder to pass - https://github.com/SumoLogic/terraform-provider-sumologic/pull/181

**Comment by tarunk2** [comment]
Thanks!

**Comment by tarunk2** [comment]
@seansain I didn't seem to have permission to push a branch to the main repo. Can you pls grant me the permissions?

**Comment by seansain** [comment]
Added you yesterday, you should have permissions now.

**Comment by tarunk2** [comment]
Thanks!

**Pull request merged**
