### PR TITLE
Adding support for Kinesis Metric Source

### PR DESCRIPTION
**Pull request by AvadheshKaria**
Added provider for kinesis metric source.

### CODE REVIEW

**Comment by AvadheshKaria** [comment]
Hi @seansain 

Looks like most of the suggested changes are from autogenerated code, can you please suggest what is the way forward.

```
% tfproviderlint ./...
/Users/akaria/go/src/SumoLogic/terraform-provider-sumologic/sumologic/resource_sumologic_role_test.go:1:1: AT012: file contains multiple acceptance test name prefixes: [TestAccSumologicRole TestAccRole]
/Users/akaria/go/src/SumoLogic/terraform-provider-sumologic/sumologic/resource_sumologic_user_test.go:1:1: AT012: file contains multiple acceptance test name prefixes: [TestAccSumologicUser TestAccUser]
/Users/akaria/go/src/SumoLogic/terraform-provider-sumologic/sumologic/resource_sumologic_subdomain_test.go:1:1: AT012: file contains multiple acceptance test name prefixes: [TestAccSumologicSubdomain TestAccSubdomain]
/Users/akaria/go/src/SumoLogic/terraform-provider-sumologic/sumologic/resource_sumologic_monitors_library_monitor_test.go:1:1: AT012: file contains multiple acceptance test name prefixes: [TestAccSumologicMonitorsLibraryMonitor TestAccMonitorsLibraryMonitor]
/Users/akaria/go/src/SumoLogic/terraform-provider-sumologic/sumologic/resource_sumologic_field_test.go:1:1: AT012: file contains multiple acceptance test name prefixes: [TestAccSumologicField TestAccField]
/Users/akaria/go/src/SumoLogic/terraform-provider-sumologic/sumologic/resource_sumologic_extraction_rule_test.go:1:1: AT012: file contains multiple acceptance test name prefixes: [TestAccSumologicFieldExtractionRule TestAccFieldExtractionRule]
/Users/akaria/go/src/SumoLogic/terraform-provider-sumologic/sumologic/resource_sumologic_ingest_budget_v2_test.go:1:1: AT012: file contains multiple acceptance test name prefixes: [TestAccSumologicIngestBudgetV2 TestAccIngestBudgetV2]
/Users/akaria/go/src/SumoLogic/terraform-provider-sumologic/sumologic/resource_sumologic_lookup_table_test.go:1:1: AT012: file contains multiple acceptance test name prefixes: [TestAccSumologicLookupTable TestAccLookupTable]

```

**Comment by seansain** [comment]
feel free to ignore those linter errors - fixing them in #178

**Review by vsinghal13 — COMMENTED** [review]
LGTM, please add the documentation page as well for the new resource. It needs to be added here: https://github.com/SumoLogic/terraform-provider-sumologic/tree/master/website/docs/r

**Comment by AvadheshKaria** [comment]
> LGTM, please add the documentation page as well for the new resource. It needs to be added here: https://github.com/SumoLogic/terraform-provider-sumologic/tree/master/website/docs/r

Added documentation

**Review by vsinghal13 — APPROVED** [review]

**Pull request merged**
