### PR TITLE
Feature - Import Partitions

### PR DESCRIPTION
**Pull request by Jamian**
* Added import partition support using the ImportStatePassthrough so it relies on the Read functionality.
* Updated docs to have Import section.

### CODE REVIEW

**Review by sumovishal — APPROVED** [review]
lgtm, thanks for adding this.

**Comment by sumovishal** [comment]
You wanna pull the latest master. Linter error was fixed recently https://github.com/SumoLogic/terraform-provider-sumologic/pull/123

**Comment by seansain** [comment]
I can finish up fixing this PR.

**Comment by seansain** [comment]
Thanks for the contribution!

**Comment by seansain** [comment]
moved to #126

**Pull request closed without merging**
