### PR TITLE
Update cloud_to_cloud_source.html.markdown

### PR DESCRIPTION
**Pull request by vsinghal13**

### CODE REVIEW

**Review by maimaisie — APPROVED** [review]

**Comment by vsinghal13** [comment]
@seansain the continuous-integration/travis CI job has not completed for the past 4 hours. Could you please take a look?

**Comment by seansain** [comment]
@vsinghal13 Should be fixed now.

**Comment by vsinghal13** [comment]
@seansain could you do I quick release with the new documentation?

**Comment by seansain** [comment]
releasing now

**Pull request merged**
